export const FETCH_STARSHIPS = 'FETCH_STARSHIPS';
export const SEARCH_STARSHIPS = 'SEARCH_STARSHIPS';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const DELETE_FROM_COMPARE = 'DELETE_FROM_COMPARE';
export const FETCH_STARSHIP = 'FETCH_STARSHIP';